"""Add user profile fields

Revision ID: 0942d618c3ca
Revises: cfc283dc177f
Create Date: 2025-12-14 15:34:57.783742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0942d618c3ca'
down_revision = 'cfc283dc177f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discriminator', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('avatar')
        batch_op.drop_column('discriminator')

    # ### end Alembic commands ###
